import { ECO_DRR, HOME } from "./projects.js";

export const EXPOSURE_LAYERS = [
  {
    id: "MX-6YLMU-U4WXC-2JJD7",
    key: "population",
    label: "Population",
    type: "rt",
    desc: "Population distribution (HRSL/GHSL 2022).",
    source: "High Resolution Settlement Layer / GHSL 2022 (Meta / EU Joint Research Centre).",
    sourceUrl: "https://human-settlement.emergency.copernicus.eu/",
    project: ECO_DRR,
  },
  {
    // TODO: move this view into the ECO_DRR project. Currently in HOME project
    // which the SDK cannot load (single-project architecture). Disabled until
    // data is consolidated.
    id: "MX-KG1JB-OI13A-6RHKN",
    key: "land-cover",
    label: "Land Cover",
    type: "cc",
    desc: "ESA WorldCover 10m (2021). Sentinel-1/2 based.",
    source: "ESA WorldCover 10m (2021), CC BY 4.0.",
    sourceUrl: "https://esa-worldcover.org/",
    note: "Disabled — view is in the MapX HOME project; cannot load until data is moved to the ECO-DRR project.",
    project: HOME,
    disabled: true,
  },
  {
    id: "MX-8F9EB-10D0B-93564",
    key: "forests",
    label: "Forests",
    type: "rt",
    desc: "Global forest coverage (MODIS, 2020).",
    source: "MODIS Global Forest Cover 2020 via MapX.",
    sourceUrl: "https://lpdaac.usgs.gov/products/mod44bv006/",
    project: ECO_DRR,
  },
  {
    id: "MX-AB65A-A5AD3-06D68",
    key: "mangroves",
    label: "Mangroves",
    type: "rt",
    desc: "Global Mangrove Watch (1996-2016).",
    source: "Global Mangrove Watch, JAXA (1996-2016).",
    sourceUrl: "https://www.globalmangrovewatch.org/",
    project: ECO_DRR,
  },
  {
    id: "MX-726D3-C0F95-0D97A",
    key: "coral-reefs",
    label: "Coral Reefs",
    type: "rt",
    desc: "Global coral reef distribution.",
    source: "UNEP-WCMC / IMaRS-USF Global Coral Reef dataset.",
    sourceUrl: "https://data.unep-wcmc.org/datasets/1",
    project: ECO_DRR,
  },
  {
    id: null,
    key: "roads-rail",
    label: "Roads & Rail",
    type: "vt",
    desc: "Global road and rail network.",
    source: "OpenStreetMap contributors (ODbL).",
    sourceUrl: "https://www.openstreetmap.org/",
    note: "Disabled — MapX view ID not yet assigned.",
    disabled: true,
  },
  {
    id: null,
    key: "power-plants",
    label: "Power Plants",
    type: "vt",
    desc: "WRI Global Power Plants Database.",
    source: "WRI Global Power Plants Database (CC BY 4.0).",
    sourceUrl: "https://datasets.wri.org/dataset/globalpowerplantdatabase",
    note: "Disabled — MapX view ID not yet assigned.",
    disabled: true,
  },
];
