import { ECO_DRR, HOME } from "./projects.js";

export const EXPOSURE_LAYERS = [
  {
    id: "MX-6YLMU-U4WXC-2JJD7",
    key: "population",
    label: "Population",
    type: "rt",
    desc: "Population distribution (HRSL/GHSL 2022).",
    source: "High Resolution Settlement Layer (Meta / CIESIN); GHSL 2022 (EU Joint Research Centre).",
    sourceUrl: "https://human-settlement.emergency.copernicus.eu/",
    citation: "Meta & CIESIN (2022): High Resolution Settlement Layer. / Pesaresi, M. et al. (2023): GHSL Data Package 2023. JRC Technical Report EUR 31741 EN.",
    license: "CC BY 4.0",
    project: ECO_DRR,
  },
  {
    // TODO: move this view into the ECO_DRR project. Currently in HOME project
    // which the SDK cannot load (single-project architecture). Disabled until
    // data is consolidated.
    id: "MX-KG1JB-OI13A-6RHKN",
    key: "land-cover",
    label: "Land Cover",
    type: "cc",
    desc: "ESA WorldCover 10m (2021). Sentinel-1/2 based.",
    source: "ESA WorldCover 10 m 2021 (European Space Agency).",
    sourceUrl: "https://esa-worldcover.org/",
    citation: "Zanaga, D. et al. (2022): ESA WorldCover 10 m 2021 v200. doi:10.5281/zenodo.7254221.",
    license: "CC BY 4.0",
    note: "Awaiting data — view is in the MapX HOME project; cannot load until data is moved to the ECO-DRR project.",
    project: HOME,
    status: "disabled-awaiting-data",
  },
  {
    id: "MX-8F9EB-10D0B-93564",
    key: "forests",
    label: "Forests",
    type: "rt",
    desc: "Global forest coverage (MODIS, 2020).",
    source: "MODIS Global Vegetation Continuous Fields (NASA LP DAAC).",
    sourceUrl: "https://lpdaac.usgs.gov/products/mod44bv006/",
    citation: "DiMiceli, C. et al. (2021): MOD44B.006 Terra Vegetation Continuous Fields Yearly Global 250m. NASA LP DAAC, Oak Ridge.",
    license: "Public Domain",
    project: ECO_DRR,
  },
  {
    id: "MX-AB65A-A5AD3-06D68",
    key: "mangroves",
    label: "Mangroves",
    type: "rt",
    desc: "Global Mangrove Watch (1996-2016).",
    source: "Global Mangrove Watch (JAXA / Aberystwyth University).",
    sourceUrl: "https://www.globalmangrovewatch.org/",
    citation: "Bunting, P. et al. (2018): The Global Mangrove Watch — A New 2010 Global Baseline of Mangrove Extent. Remote Sensing, 10(10): 1669.",
    license: "CC BY 4.0",
    project: ECO_DRR,
  },
  {
    id: "MX-726D3-C0F95-0D97A",
    key: "coral-reefs",
    label: "Coral Reefs",
    type: "rt",
    desc: "Global coral reef distribution.",
    source: "UNEP-WCMC / IMaRS-USF Global Coral Reef dataset.",
    sourceUrl: "https://wcmc.io/coral-reef-data",
    citation: "UNEP-WCMC, WorldFish Centre, WRI, TNC (2021): Global distribution of warm-water coral reefs. Ocean+ Library. doi:10.34892/t2wk-5t17.",
    license: "CC BY-NC-SA 3.0",
    project: ECO_DRR,
    note: "Pending removal — retained in the prototype inventory while category scope is under review.",
    status: "disabled-pending-removal",
  },
  {
    id: null,
    key: "roads-rail",
    label: "Roads & Rail",
    type: "vt",
    desc: "Global road and rail network.",
    source: "OpenStreetMap contributors (Open Database License).",
    sourceUrl: "https://www.openstreetmap.org/",
    citation: "OpenStreetMap contributors (2024): OpenStreetMap Data. openstreetmap.org.",
    license: "ODbL 1.0",
    note: "Awaiting data — MapX view ID not yet assigned.",
    status: "disabled-awaiting-data",
  },
  {
    id: null,
    key: "power-plants",
    label: "Power Plants",
    type: "vt",
    desc: "WRI Global Power Plants Database.",
    source: "WRI Global Power Plants Database.",
    sourceUrl: "https://datasets.wri.org/dataset/globalpowerplantdatabase",
    citation: "Byers, L. et al. (2019): A Global Database of Power Plants. World Resources Institute, Washington D.C.",
    license: "CC BY 4.0",
    note: "Awaiting data — MapX view ID not yet assigned.",
    status: "disabled-awaiting-data",
  },
];
