import { ECO_DRR } from "./projects.js";

export const HAZARD_LAYERS = [
  {
    id: "MX-V07LO-829XA-4BIZ8",
    label: "River Flooding",
    type: "rt",
    desc: "Flood hazard 25yr return period (GAR model). Depth in mm.",
    project: ECO_DRR,
    legend: [
      { color: "#f7fbff", label: "<= 10 mm" },
      { color: "#d2e3f3", label: "50 mm" },
      { color: "#9fcae1", label: "100 mm" },
      { color: "#6baed6", label: "200 mm" },
      { color: "#3182bd", label: "500 mm" },
      { color: "#1c6cb1", label: "1000 mm" },
      { color: "#0b4d94", label: "2000 mm" },
      { color: "#08306b", label: "5000 mm" },
      { color: "#041e42", label: "> 5000 mm" },
    ],
  },
  {
    id: "MX-21A2A-BED99-D8D78",
    label: "River Flood Frequency",
    type: "rt",
    desc: "Annual frequency of river floods, 25-1000yr return period.",
    project: ECO_DRR,
  },
  {
    id: "MX-8C214-22C3A-82165",
    label: "Cyclone Surge Exposure",
    type: "rt",
    desc: "Annual physical exposure to surges from cyclones.",
    project: ECO_DRR,
  },
  {
    id: "MX-E180C-5B012-AFC77",
    label: "Tropical Cyclone Frequency",
    type: "rt",
    desc: "Cyclone wind speed probabilities (STORM dataset).",
    project: ECO_DRR,
  },
  {
    id: "MX-10AE5-746D1-76777",
    label: "Tropical Cyclone Exposure",
    type: "rt",
    desc: "Annual physical exposure to tropical cyclones.",
    project: ECO_DRR,
  },
  {
    id: "MX-04E66-2E550-81068",
    label: "Landslide Exposure",
    type: "rt",
    desc: "Annual exposure to landslides (earthquake + precipitation triggered).",
    project: ECO_DRR,
  },
  {
    id: "MX-05247-89997-66A64",
    label: "Landslide Frequency",
    type: "rt",
    desc: "Annual frequency of landslides.",
    project: ECO_DRR,
  },
  {
    id: "MX-YLZJG-JAIID-V27X5",
    label: "Earthquakes (live)",
    type: "cc",
    desc: "USGS Mag >= 5.5, past 30 days. Updated every 15 min.",
    project: ECO_DRR,
  },
  {
    id: "MX-F0DEE-12D97-6447B",
    label: "Tsunami Exposure",
    type: "rt",
    desc: "Annual physical exposure to tsunamis.",
    project: ECO_DRR,
  },
  {
    id: "MX-D7314-A5044-83377",
    label: "Tsunami Frequency",
    type: "rt",
    desc: "Annual frequency of tsunamis.",
    project: ECO_DRR,
  },
];
