import { ECO_DRR } from "./projects.js";

export const HAZARD_LAYERS = [
  {
    id: null,
    key: "river-flooding",
    label: "River Flooding",
    type: "rt",
    desc: "Flood hazard from the GAR model.",
    source: "GAR/PREVIEW platform (UNEP/GRID-Geneva) via MapX. Underlying data: WRI Aqueduct Floods; JRC Global River Flood Hazard Maps.",
    sourceUrl: "https://unepgrid.ch/en/activity/1BDE1705",
    citation: "Ward, P.J. et al. (2020): Aqueduct Floods Methodology. WRI Technical Note, Washington D.C. / Baugh, C. et al. (2024): Global river flood hazard maps. JRC. doi:10.2905/jrc-floods-floodmapgl.",
    license: "CC BY 4.0",
    project: ECO_DRR,
    sources: [
      {
        id: "MX-V07LO-829XA-4BIZ8",
        label: "Depth",
        desc: "Flood depth in mm, 25yr return period.",
        legend: [
          { color: "#f7fbff", label: "<= 10 mm" },
          { color: "#d2e3f3", label: "50 mm" },
          { color: "#9fcae1", label: "100 mm" },
          { color: "#6baed6", label: "200 mm" },
          { color: "#3182bd", label: "500 mm" },
          { color: "#1c6cb1", label: "1000 mm" },
          { color: "#0b4d94", label: "2000 mm" },
          { color: "#08306b", label: "5000 mm" },
          { color: "#041e42", label: "> 5000 mm" },
        ],
      },
      {
        id: "MX-21A2A-BED99-D8D78",
        label: "Frequency",
        desc: "Annual frequency of river floods, 25-1000yr return period.",
      },
      {
        id: "MX-4918F-8A0E5-AF76B",
        label: "Exposure",
        desc: "Annual physical exposure to river floods.",
      },
    ],
    widget: { type: "sub-tabs", label: "Metric" },
  },
  {
    id: null,
    key: "earthquake-pga",
    label: "Earthquake PGA",
    type: "rt",
    desc: "Peak Ground Acceleration from the GEM Global Seismic Hazard Map.",
    source: "Global Earthquake Model (GEM) Foundation.",
    sourceUrl: "https://www.globalquakemodel.org/gem",
    citation: "Pagani, M. et al. (2018): Global Earthquake Model (GEM) Seismic Hazard Map. Earthquake Spectra, 34(4): 1281–1296. doi:10.1193/160117EQS316M.",
    license: "CC BY-NC-SA 4.0",
    project: ECO_DRR,
    sources: [
      { id: "MX-J3YTW-RUQN3-40P87", label: "250 yr" },
      { id: "MX-4XSGY-9URYF-WMICZ", label: "475 yr" },
      { id: "MX-KE2UX-GL8CM-IZSIA", label: "975 yr" },
      { id: "MX-SFF5U-3O2XL-SAIL9", label: "1500 yr" },
      { id: "MX-MWJ8Z-JYVYX-N9T0T", label: "2475 yr" },
    ],
    widget: { type: "stepped-slider", label: "Return period" },
  },
  {
    id: "MX-YLZJG-JAIID-V27X5",
    key: "earthquakes-live",
    label: "Earthquakes (live)",
    type: "cc",
    desc: "USGS Mag >= 5.5, past 30 days. Updated every 15 min.",
    source: "USGS Earthquake Hazards Program.",
    sourceUrl: "https://earthquake.usgs.gov/earthquakes/feed/",
    citation: "USGS Earthquake Hazards Program. Advanced National Seismic System Comprehensive Earthquake Catalog (ComCat). earthquake.usgs.gov/earthquakes/feed/",
    license: "Public Domain (U.S. Government)",
    project: ECO_DRR,
  },
  {
    id: "MX-8C214-22C3A-82165",
    key: "cyclone-surge",
    label: "Cyclone Surge Exposure",
    type: "rt",
    desc: "Annual physical exposure to surges from cyclones.",
    source: "GAR/PREVIEW platform (UNEP/GRID-Geneva) via MapX.",
    sourceUrl: "https://unepgrid.ch/en/activity/1BDE1705",
    citation: "GAR/PREVIEW Platform, UNEP/GRID-Geneva. Based on Ward, P.J. et al. (2020): Aqueduct Floods Methodology. WRI.",
    license: "CC BY 4.0",
    project: ECO_DRR,
  },
  {
    id: null,
    key: "tropical-cyclones",
    label: "Tropical Cyclones",
    type: "rt",
    desc: "Cyclone wind speed and physical exposure.",
    source: "STORM Tropical Cyclone dataset (Bloemendaal et al.); IRIS Imperial College Storm Model.",
    sourceUrl: "https://www.nature.com/articles/s41597-020-0381-2",
    citation: "Bloemendaal, N. et al. (2020): Generation of a global synthetic tropical cyclone hazard dataset using STORM. Scientific Data, 7: 40. doi:10.1038/s41597-020-0381-2.",
    license: "CC0 1.0 (STORM) / CC BY 4.0 (IRIS)",
    project: ECO_DRR,
    sources: [
      {
        id: "MX-E180C-5B012-AFC77",
        label: "Frequency",
        desc: "Cyclone wind speed probabilities (STORM dataset).",
      },
      {
        id: "MX-10AE5-746D1-76777",
        label: "Exposure",
        desc: "Annual physical exposure to tropical cyclones.",
      },
    ],
    widget: { type: "sub-tabs", label: "Metric" },
  },
  {
    id: null,
    key: "landslides",
    label: "Landslides",
    type: "rt",
    desc: "Earthquake and precipitation triggered landslides.",
    source: "GAR/PREVIEW platform (UNEP/GRID-Geneva) via MapX.",
    sourceUrl: "https://unepgrid.ch/en/activity/1BDE1705",
    citation: "GAR/PREVIEW Platform, UNEP/GRID-Geneva.",
    license: "UNEP",
    project: ECO_DRR,
    sources: [
      {
        id: "MX-04E66-2E550-81068",
        label: "Exposure",
        desc: "Annual exposure to landslides.",
      },
      {
        id: "MX-05247-89997-66A64",
        label: "Frequency",
        desc: "Annual frequency of landslides.",
      },
    ],
    widget: { type: "sub-tabs", label: "Metric" },
  },
  {
    id: null,
    key: "tsunamis",
    label: "Tsunamis",
    type: "rt",
    desc: "Tsunami exposure and frequency.",
    source: "GAR/PREVIEW platform (UNEP/GRID-Geneva) via MapX.",
    sourceUrl: "https://unepgrid.ch/en/activity/1BDE1705",
    citation: "GAR/PREVIEW Platform, UNEP/GRID-Geneva.",
    license: "UNEP",
    project: ECO_DRR,
    sources: [
      {
        id: "MX-F0DEE-12D97-6447B",
        label: "Exposure",
        desc: "Annual physical exposure to tsunamis.",
      },
      {
        id: "MX-D7314-A5044-83377",
        label: "Frequency",
        desc: "Annual frequency of tsunamis.",
      },
    ],
    widget: { type: "sub-tabs", label: "Metric" },
  },
];
