import { ECO_DRR } from "./projects.js";

const RISK_CITATION = "Derived composite layer. See component hazard and exposure layer citations.";
const RISK_LICENSE = "Derived (see component layers)";
const CDRI_SOURCE = "CDRI / GIRI catalogue (exact dataset and MapX delivery pending confirmation).";
const CDRI_URL = "https://giri.unepgrid.ch/map?list=explore";
const CDRI_CITATION = "Placeholder entry based on programme-team feedback; final CDRI dataset reference to be confirmed.";
const CDRI_LICENSE = "TBD";

export const RISK_LAYERS = [
  {
    // TODO: replace with a composite risk view ID once available in MapX.
    // These IDs are currently shared with hazard exposure sources, which
    // corrupts toggle state. Disabled until dedicated risk views exist.
    id: null,
    key: "risk-river-flood",
    label: "River Flood Exposure",
    type: "rt",
    desc: "Annual physical exposure to river floods.",
    source: "Derived from hazard and exposure layers (GAR/PREVIEW).",
    sourceUrl: "https://unepgrid.ch/en/activity/1BDE1705",
    citation: RISK_CITATION,
    license: RISK_LICENSE,
    note: "Awaiting data — dedicated risk view ID not yet available in MapX; current ID conflicts with hazard layer.",
    project: ECO_DRR,
    status: "disabled-awaiting-data",
  },
  {
    id: null,
    key: "risk-cyclone",
    label: "Cyclone Exposure",
    type: "rt",
    desc: "Annual physical exposure to tropical cyclones.",
    source: "Derived from hazard and exposure layers (GAR/PREVIEW).",
    sourceUrl: "https://unepgrid.ch/en/activity/1BDE1705",
    citation: RISK_CITATION,
    license: RISK_LICENSE,
    note: "Awaiting data — dedicated risk view ID not yet available in MapX; current ID conflicts with hazard layer.",
    project: ECO_DRR,
    status: "disabled-awaiting-data",
  },
  {
    id: null,
    key: "risk-landslide",
    label: "Landslide Exposure",
    type: "rt",
    desc: "Annual physical exposure to landslides.",
    source: "Derived from hazard and exposure layers (GAR/PREVIEW).",
    sourceUrl: "https://unepgrid.ch/en/activity/1BDE1705",
    citation: RISK_CITATION,
    license: RISK_LICENSE,
    note: "Awaiting data — dedicated risk view ID not yet available in MapX; current ID conflicts with hazard layer.",
    project: ECO_DRR,
    status: "disabled-awaiting-data",
  },
  {
    id: null,
    key: "cdri-aal-infrastructure-existing-climate",
    label: "CDRI AAL per Building & Infrastructure (Existing climate)",
    type: "rt",
    desc: "Average annual loss across buildings and infrastructure under existing climate assumptions.",
    source: CDRI_SOURCE,
    sourceUrl: CDRI_URL,
    citation: CDRI_CITATION,
    license: CDRI_LICENSE,
    note: "Awaiting data — placeholder added from William feedback while exact CDRI layer and MapX delivery are being confirmed.",
    project: ECO_DRR,
    status: "disabled-awaiting-data",
  },
  {
    id: null,
    key: "cdri-aal-infrastructure-lower-bound",
    label: "CDRI AAL per Building & Infrastructure (Lower bound)",
    type: "rt",
    desc: "Average annual loss across buildings and infrastructure using the lower-bound CDRI scenario.",
    source: CDRI_SOURCE,
    sourceUrl: CDRI_URL,
    citation: CDRI_CITATION,
    license: CDRI_LICENSE,
    note: "Awaiting data — placeholder added from William feedback while exact CDRI layer and MapX delivery are being confirmed.",
    project: ECO_DRR,
    status: "disabled-awaiting-data",
  },
  {
    id: null,
    key: "cdri-aal-infrastructure-upper-bound",
    label: "CDRI AAL per Building & Infrastructure (Upper bound)",
    type: "rt",
    desc: "Average annual loss across buildings and infrastructure using the upper-bound CDRI scenario.",
    source: CDRI_SOURCE,
    sourceUrl: CDRI_URL,
    citation: CDRI_CITATION,
    license: CDRI_LICENSE,
    note: "Awaiting data — placeholder added from William feedback while exact CDRI layer and MapX delivery are being confirmed.",
    project: ECO_DRR,
    status: "disabled-awaiting-data",
  },
  {
    id: null,
    key: "cdri-aal-flood",
    label: "CDRI AAL (Flood)",
    type: "rt",
    desc: "Average annual loss for flood risk in the CDRI catalogue.",
    source: CDRI_SOURCE,
    sourceUrl: CDRI_URL,
    citation: CDRI_CITATION,
    license: CDRI_LICENSE,
    note: "Awaiting data — hazard-specific AAL placeholder added from William feedback; exact layer still to be confirmed.",
    project: ECO_DRR,
    status: "disabled-awaiting-data",
  },
  {
    id: null,
    key: "cdri-aal-earthquake",
    label: "CDRI AAL (Earthquake)",
    type: "rt",
    desc: "Average annual loss for earthquake risk in the CDRI catalogue.",
    source: CDRI_SOURCE,
    sourceUrl: CDRI_URL,
    citation: CDRI_CITATION,
    license: CDRI_LICENSE,
    note: "Awaiting data — hazard-specific AAL placeholder added from William feedback; exact layer still to be confirmed.",
    project: ECO_DRR,
    status: "disabled-awaiting-data",
  },
  {
    id: null,
    key: "cdri-aal-cyclone",
    label: "CDRI AAL (Cyclone)",
    type: "rt",
    desc: "Average annual loss for cyclone risk in the CDRI catalogue.",
    source: CDRI_SOURCE,
    sourceUrl: CDRI_URL,
    citation: CDRI_CITATION,
    license: CDRI_LICENSE,
    note: "Awaiting data — hazard-specific AAL placeholder added from William feedback; exact layer still to be confirmed.",
    project: ECO_DRR,
    status: "disabled-awaiting-data",
  },
  {
    id: null,
    key: "cdri-pml-flood-100yr",
    label: "CDRI PML 1:100 (Flood)",
    type: "rt",
    desc: "Probable maximum loss for a 1:100-year flood event.",
    source: CDRI_SOURCE,
    sourceUrl: CDRI_URL,
    citation: CDRI_CITATION,
    license: CDRI_LICENSE,
    note: "Awaiting data — 1:100 flood PML placeholder added from William feedback; exact layer still to be confirmed.",
    project: ECO_DRR,
    status: "disabled-awaiting-data",
  },
  {
    id: null,
    key: "cdri-pml-earthquake-100yr",
    label: "CDRI PML 1:100 (Earthquake)",
    type: "rt",
    desc: "Probable maximum loss for a 1:100-year earthquake event.",
    source: CDRI_SOURCE,
    sourceUrl: CDRI_URL,
    citation: CDRI_CITATION,
    license: CDRI_LICENSE,
    note: "Awaiting data — 1:100 earthquake PML placeholder added from William feedback; exact layer still to be confirmed.",
    project: ECO_DRR,
    status: "disabled-awaiting-data",
  },
  {
    id: null,
    key: "cdri-pml-cyclone-100yr",
    label: "CDRI PML 1:100 (Cyclone)",
    type: "rt",
    desc: "Probable maximum loss for a 1:100-year cyclone event.",
    source: CDRI_SOURCE,
    sourceUrl: CDRI_URL,
    citation: CDRI_CITATION,
    license: CDRI_LICENSE,
    note: "Awaiting data — 1:100 cyclone PML placeholder added from William feedback; exact layer still to be confirmed.",
    project: ECO_DRR,
    status: "disabled-awaiting-data",
  },
];
